services:
  db:
    image: postgres
    env_file:
      - .env
    ports:
      - "5432:5432"

  web:
    build: .
    volumes:
      - .:/sibdev
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db