# Generated by Django 4.2 on 2023-04-18 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_deal_delete_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='total',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
